// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zpjxfsmopjjwkdodyoyh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpwanhmc21vcGpqd2tkb2R5b3loIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2Nzc0NTEsImV4cCI6MjA3MzI1MzQ1MX0.tdSqgMrj9Qduvm4_QXSY531JSZs7S5ANUoRR3Mx_DkI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});